In [1]:
import numpy as np
import time

Creating array from list

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)
arr_2d = np.array([[1,2,3], [4,5,6]])
print("1D array: ", arr_2d)

List Vs Numpy Array

In [ ]:
py_list = [1,2,3]
print(py_list * 2)

np_array = np.array([1,2,3])
print (np_array * 2)

In [ ]:
start = time.time()
py_list = [i*2 for i in range(10000000)]
print(time.time()-start)
start = time.time()
np_array = np.arange(10000000) * 2
print(time.time() - start)

Creating Arrays from Scratch

In [ ]:
zeros = np.zeros((3,4))
print(zeros)
ones = np.ones((2,3))
print(ones)

full = np.full((2,3), 7)
print(full)

random = np.random.random((2,3))
print(random)
sequence = np.arange(0,10,2)
print(sequence)

### vector, matix and tensor

In [ ]:
vector = np.array([1,2,3])
print("Vector: ", vector)
matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor: ", tensor)

### Array Properties

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print("Shape: ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

### Array Reshaping

In [10]:
arr = np.arange(12)
print(arr)
reshaped = arr.reshape((3,4))
print("Reshaped: ", reshaped)
flattened = reshaped.flatten()
print(flattened)
reveled = reshaped.ravel()
print(reveled)
transpose = reshaped.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
