In [2]:
import numpy as np

### Indexing and Slicing

In [3]:
arr = np.array([1,2,3,4,5,6,7,8])
print("Basic Slicing", arr[2:7])
print("Slicing with steps: ", arr[1:8:2])
print("Negative Indexing",arr[-3])

Basic Slicing [3 4 5 6 7]
Slicing with steps:  [2 4 6 8]
Negative Indexing 6


In [4]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr_2d[1,2])
print("Entire Row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 0])

6
Entire Row:  [4 5 6]
Entire column:  [1 4 7]


### Sorting

In [5]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("sorted array: ", np.sort(unsorted))
arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print(np.sort(arr_2d_unsorted, axis = 0))

sorted array:  [1 1 2 3 4 5 6 9]
[[1 1]
 [2 2]
 [3 3]]


### Filtering

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8])
even_number = numbers[numbers%2 == 0]
print(even_number)

[2 4 6 8]


### filter and mask

In [7]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [6 7 8]


### Fancy indexing Vs np.where()

In [8]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[1 3 5]
NP where [6 7 8]


In [9]:
condition_array = np.where(numbers > 5, numbers*2, numbers) # research this
print(condition_array) 

[ 1  2  3  4  5 12 14 16]


### Adding and removing data

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1 ,arr2))
print(combined)

[1 2 3 4 5 6]


### array  compatibity

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9]) #SHAPE OF ARRAY

True


### Adding rows and column

In [14]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(with_new_row)

new_col = ([[7],[8]])
with_new_column = np.hstack((original, new_col))
print(with_new_column)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [16]:
arr = np.array([1,2,3,4,5,6,7,8])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5 6 7 8]
